### ISSUE TITLE
Implementer en dynamisk lønnsslipp

### ISSUE THREAD

**Issue by Trulsaa** [Alv-no/alvtime#121]
Visning av dynamisk lønnslipp

**Comment by FredrikAugust** [comment]
Kan denne lukkes? @Trulsaa

**Comment by Trulsaa** [comment]
Jeg oppdaterte beskrivelsen litt. Merge requesten det refereres til er ikke relatert. Vet ikke hvorfor den er knyttet til dette issuet. Jeg har fortsatt lyst på denne futuren :)

**Comment by palbock** [comment]
Duplikat av #352
