### ISSUE TITLE
View til uttak av overtidstimer

### ISSUE THREAD

**Issue by Trulsaa** [Alv-no/alvtime#122]

**Comment by niclasalv** [comment]
![timebank](https://user-images.githubusercontent.com/60391148/81149431-7d5b2d00-8f7e-11ea-9210-93e9e4efdd73.png)

**Comment by niclasalv** [comment]
@martiskj 
https://alvno.sharepoint.com/:w:/s/Alvdisk/EZxjsXYZeAxLqBIhz6k4_gABl6ytsAZKWMyt2GDl34B4AQ?e=bufznn
