### ISSUE TITLE
Legge til "prosjekt" i brukergrensesnittet

### ISSUE THREAD

**Issue by MichaelSvensen** [Alv-no/alvtime#134]
I dagens løsninger det ikke mulig å skille på prosjekt hos samme kunde hvis task ikke er forskjellig når du fører timer.
![Screenshot_20200602-105154_Samsung Internet](https://user-images.githubusercontent.com/40336103/83506785-ea9fa680-a4c7-11ea-9325-0f0130643289.jpg)

![Screenshot_20200602-105244_Samsung Internet](https://user-images.githubusercontent.com/40336103/83506708-cd6ad800-a4c7-11ea-9da1-4808ac0991de.jpg)

**Comment by Trulsaa** [comment]
Duplicate of #129
