### ISSUE TITLE
Umulig å velge en HourInput på mobil når Task er lang

### ISSUE THREAD

**Issue by Trulsaa** [Alv-no/alvtime#138]

**Comment by FredrikAugust** [comment]
Kunne du forklart litt mer nøyaktig hva av problemet er, og gjerne legge med noen bilder eller videoer av problemet?

**Comment by Trulsaa** [comment]
Dette ble nok fikset av @rsletta når han laget bedre Task visning med expand. Jeg klarer i allefall ikke å reprodusere
