### ISSUE TITLE
Aktiviteter kan ikke registreres eller fjernes som favoritt

### ISSUE THREAD

**Issue by barmartland** [Alv-no/alvtime#145]
![KanIkkeRegistrereNyeAktiviteter_UtenNavn](https://user-images.githubusercontent.com/27969994/91696557-0884b200-eb70-11ea-8917-075110981d3e.gif)

Følgende feilmelding dukket opp etterhvert:
"JSON.parse: unexpected end of data at line 1 column 1 of the JSON data -> JSON.parse: unexpected end of data at line 1 column 1 of the JSON data"

Når jeg så refreshet siden fungerte alt som forventet igjen.

**Comment by Trulsaa** [comment]
Dette fungerer igjen nå. Jeg lukker denne under antagelsen av at det hadde noe med endringene som har skjedd i backend å gjøre den siste tiden.
