### ISSUE TITLE
Add timestamp for when hours where registered

### ISSUE THREAD

**Issue by barmartland** [Alv-no/alvtime#170]
Today we don't know when a user entered their hours. So if we want to only pull data out from AlvTime since we last read there is no way of actually doing this. This is a super nice to have when it comes to data extraction.

It could also be useful in other scenarios to notify people that it is "x amounts of days" since they last registered their hours.

**Comment by FredrikAugust** [comment]
Jeg lukker denne siden `hours`-tabellen inkluderer et `date`-felt. Du får heller åpne det igjen, @palbock90 dersom jeg misforstod.

EDIT:
jeg lukker ikke. misforstod issuet

**Comment by palbock** [comment]
Tror det som var ønsket var et felt for når personen faktisk skrev inn timen i Alvtime, ikke hvilken dato timene er registrert på som er det vi har nå.

**Comment by FredrikAugust** [comment]
Ahaaa, da lukker jeg ikke!

**Comment by palbock** [comment]
Bør også legges inn på EarnedOvertime-tabell
