### ISSUE TITLE
Sette opp logging for container i Azure

### ISSUE THREAD

**Issue by palbock** [Alv-no/alvtime#174]
Kan bruke azure container monitoring solution + log analytics workspace. Mulig funker bedre med AKS.

Logging fungerer delvis uten container monitoring, men med log analytics. Får opp logs når jeg kaller fra Postman, men de inneholder ikke innholdet i meldingene som kommer frem og tilbake. Får ingen logs når jeg fører timer i nettsiden. Har ikke forsøkt å analysere loggene detaljert i log analytics workspace.

OBS: Log analytics workspace koster penger.

**Comment by FredrikAugust** [comment]
Ser Azure har [Container insights](https://docs.microsoft.com/en-gb/azure/azure-monitor/containers/container-insights-overview), er dette noe å se på?

I så fall må vi sette et scope for dette issuet; er det kun å flippe på en feature i Azure, eller skal vi også endre hvordan logs gjøres i appen? F.eks. sette opp Application Insights, bruker Serilog, &c.

**Comment by palbock** [comment]
Dette er nok en litt stor oppgave. Det er ikke konfigurert noe som helst logging i Alvtime akkurat nå og jeg aner ikke hvordan man logger til en k8s cluster. Har ikke noen spesiell mening rundt Serilog eller andre logge-rammeverk, syns forsåvidt det innebygde fungerer fint.

**Comment by FredrikAugust** [comment]
Skjønner. Serilog var bare et tilfeldig eksempel, har ingen formening om hvorvidt det skal brukes eller ikke.

Virker da som om denne oppgaven vil innebære følgende:

- research av logging i k8s cluster, og kanskje AKS spesifikt
- implementer logging fra API til Azure Log Workspace (eller annet egnet sted)

Tenker det er en grei start, og så kan man heller bygge ut fra det?

**Comment by FredrikAugust** [comment]
Tok en titt på dette nå, og virker som om det er to enkle steg vi kan ta som vil gi mye verdi:

- skru på container insights. dette vil gi performance insights for podsene i k8s clusteret. dette er bare en knapp inne i Azure og ser ikke ut til å koste så mye. [link](https://docs.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-onboard)
- lage et application insights workspace og sende logs dit fra k8s poden til apiet. du kan også bruke en AKS-enhancer sånn at logsene inneholder informasjon om hvilken container requestet kom fra osv. [link](https://github.com/microsoft/ApplicationInsights-Kubernetes)

tror kanskje dette er en passende oppgave for @Trulsaa?

**Comment by Trulsaa** [comment]
Container insights høres ut som noe som må inn i terraform kode for at det ikke bare skal bli skrudd av igjen neste gang vi kjører terraform apply 🤷 

Jeg har ikke så my tid i disse dager. Så om det faller på meg så holder det nok med `kubectl -n alvtime logs api-xxxxxx`

**Comment by FredrikAugust** [comment]
Det må nok inn i terraform ja.

Her er guide hvis noen skulle være interesserte https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-tf-and-aks
