### ISSUE TITLE
Undersøk data som returneres fra endepunkt

### ISSUE THREAD

**Issue by palbock** [Alv-no/alvtime#175]
Undersøk om noen endepunkter returnerer mer data enn det som er nødvendig med tanke på hva frontend bruker. Kanskje noe data kan skrelles bort, kanskje noen endepunkter kan slås sammen, kanskje noen DTOer kan lages mye enklere.

**Comment by FredrikAugust** [comment]
Har du noen eksempler på hva resultatet du ønsker å se ville vært med disse endringene? Skal det gjøres noen endringer i frontend også?

**Comment by palbock** [comment]
Husker ikke heeelt hva jeg tenkte her, men jeg tror at tanken er at istedet for at frontend må hente info fra flere endepunkter og så sy det sammen selv, så kan backend gjør syingen og returnere all dataen frontend trenger i færre endepunkter.
