### ISSUE TITLE
Look into generating TypeScript client code from the swagger / OpenAPI definitions

### ISSUE THREAD

**Issue by TheKnarf** [Alv-no/alvtime#188]
Using a project like [openapi-generator](https://github.com/OpenAPITools/openapi-generator) one can generate Client code. That way the client code is always in sync with the OpenAPI definitions.

A little more work to setup, but less work in the long-run to maintain.

**Comment by Trulsaa** [comment]
Følgende komando genererer en slik client.
```bash
npx @openapitools/openapi-generator-cli generate -i https://api.test-alvtime.no/swagger/v1/swagger.json -g typescript-fetch -o generated-alvtime-api-client
```
