### ISSUE TITLE
CODEOWNER fila gjør at en eier må godkjenne

### ISSUE THREAD

**Issue by Trulsaa** [Alv-no/alvtime#206]
Det holder altså ikke at en av de andre som har blitt spurt om å gi review gjør det. 

Dette gjør at godkjenning ikke går raskt nok og kan gjøre at PR blir sett på som en barriere istedenfor en mulighet til å lære.

@TheKnarf Går det an å endre dette i en innstilling. Hvis ikke så foreslår jeg at vi fjerner CODEOWNER fila. Jeg stoler på at folk i Alv kun godkjenner ting de kan stå inne for.

**Comment by TheKnarf** [comment]
<img width="573" alt="Screenshot 2020-11-28 at 16 53 16" src="https://user-images.githubusercontent.com/213777/100519755-38a51680-319a-11eb-895d-bd4bb0b0da7f.png">

Dette er en setting jeg har skrudd på ja.

**Comment by Trulsaa** [comment]
Kan du skru det av igjen? Jeg tenker det holder at en av de som blir spurt approver. Jeg tror ikke vi har behov for noen streng kontroll av koden som skal inn i master. Jeg håper PR kan bli en god platform for kunnskapsdeling.

**Comment by TheKnarf** [comment]
Da er det skrudd av.
