### ISSUE TITLE
Implement input validation for all endpoints backend

### ISSUE THREAD

**Issue by palbock** [Alv-no/alvtime#207]
Posted timer må være positive og gå opp i halvtimer. Samme med bestilling.

Ferie må tas ut i hele dager? Kan ikke føre ferie og noe annet på samme dag

**Comment by FredrikAugust** [comment]
Ser at halvtime-eksempelet allerede ser ut til å ha en fiks her

https://github.com/Alv-no/alvtime/blob/424ca5ff26334c75f08eb6a3a52faee354ad005c/packages/api/AlvTime.Business/FlexiHours/GenericHourEntry.cs#L10

Er det noen flere av disse som har blitt fikset siden issuet ble laget?

**Comment by palbock** [comment]
Ferievalideringen tror jeg ikke er fikset, men det kan hende ikke noe trengs å gjøres der. Har forstått at det er ønskelig å kunne føre både ferie og andre ting på samme dag. Hvis man for eksempel blir tvunget til å jobbe for kunde på en dag man egentlig har tatt ut ferie. Antar det er ønskelig å bare kunne registrere hele dager på ferie.

**Comment by idatheo** [comment]
La ikke helt merke til good first issue før jeg var ferdig. Har bare lagt til validering to steder. Sikkert flere steder som gjenstår. Lite problem med Sluttdato-valideringen:
Frontend har ingen håndtering av BadRequest eller exceptions, så det ser ut som sluttdato blir registrert feil. Dersom jeg kaster exception, blir siden helt blank. Usikker på om jeg heller burde kommentere ut den koden.
