### ISSUE TITLE
Stop user from registering more than 7,5 hours on "Avspasering", "Ferie", "Sykt barn"

### ISSUE THREAD

**Issue by niclasalv** [Alv-no/alvtime#243]
Dersom en bruker prøver å føre mer enn 7.5 timer på en task som tilhører prosjektet "Fravær" eller har allerede ført 7.5 timer på en dag og så fører mer på en task som tilhører "Fravær" skal de blir stoppet fra det.

**Comment by Trulsaa** [comment]
@ragnskah Har du en oppdatering på dette issuet?
