### ISSUE TITLE
Anchore fails in workflow

### ISSUE THREAD

**Issue by palbock** [Alv-no/alvtime#251]
Anchore is currently configured to check only master branch. Releases needs to be included

**Comment by palbock** [comment]
Fails with error message:
`

push_to_docker_hub
failed 11 minutes ago in 45s
45s
Current runner version: '2.275.1'
Operating System
Virtual Environment
Prepare workflow directory
Prepare all required actions
Getting action download info
Failed to resolve action download info. Error: Unable to resolve action `anchore/scan-action@master`, unable to find version `master`
Retrying in 24.485 seconds
Failed to resolve action download info. Error: Unable to resolve action `anchore/scan-action@master`, unable to find version `master`
Retrying in 19.751 seconds
Error: Failed to resolve action download info.`

**Comment by Trulsaa** [comment]
That action has removed its master branch. The README instructs to use `anchore/scan-action@v2`
