### ISSUE TITLE
Implement a lightweight and database first migration tool

### ISSUE THREAD

**Issue by Trulsaa** [Alv-no/alvtime#354]
For example: [Umzug](https://www.npmjs.com/package/umzug) or [roundhouse](https://github.com/chucknorris/roundhouse)

Make it possible to:

1. Create SQL migration scripts
2. Run all scripts against database. Only new scripts will be run.
3. Run manually on local dev database
4. Run on test and prod environment from pipeline

**Comment by Trulsaa** [comment]
Dette hadde også løst issuet med å fjerne bruken av sql tool inne i docker imaget til databasen. Dette ville gjort det mulig å kjøre denne containeren på ARM Mac

**Comment by palbock** [comment]
Suggest using [DbUp](https://dbup.readthedocs.io/en/latest/)

EDIT: Foreslår heller EF Migrations. Vi bruker allerede Entity Framework i Alvtime og dette er bedre dokumentert og mer utbredt.
