### ISSUE TITLE
Legge håndtering av overtidsbetaling gitt lønn pr tidspunkt

### ISSUE THREAD

**Issue by idatheo** [Alv-no/alvtime#367]

**Comment by FredrikAugust** [comment]
Betyr denne endringen at kalkulering av overtidsbetaling skal skje gitt lønn i tidspunktet der overtiden ble ført?

**Comment by idatheo** [comment]
Ja, og den var egentlig for en god stund siden. Manglet bare en database. Meeen, så fikk vi nye endringer, og branchen endte langt bak, Har snakket med Lars Espen. Endringene her skal ikke inn i alvtime. Lukker issuen, og fjerner PRen
