### ISSUE TITLE
Implementer lønnsfunksjonalitet i adminpanel

### ISSUE THREAD

**Issue by palbock** [Alv-no/alvtime#379]

**Comment by FredrikAugust** [comment]
Kunne du skrevet litt mer om hva dette betyr? Hvilken funksjonalitet ønsker du?

**Comment by palbock** [comment]
Dette er litt relatert til PRen til @idatheo. Er ikke helt sikker på hvordan lederne faktisk ønsker å ha kontroll på lønn, men tanken var at dette kunne styres fra adminpanelet. Men kanskje det styres i tripletex nå?

**Comment by FredrikAugust** [comment]
Related to https://github.com/Alv-no/alvtime/pull/377

**Comment by idatheo** [comment]
Sendte melding til @lnordhus Issuen min #377 skal ikke inn i alvtime likevel. Har lukket issue og relatert PR
