### ISSUE TITLE
Brukere skal ikke kunne bruke PATs etter de har sluttet

### ISSUE THREAD

**Issue by palbock** [Alv-no/alvtime#403]
Logikk må inn i PersonalAccessTokenHandler.cs for å sjekke om bruker har sluttet

**Comment by FredrikAugust** [comment]
Gjelder dette fortsatt etter endringene jeg og @klyngen la inn? Tenker du at de ikke skal få hente ut en PAT i det hele tatt?

**Comment by palbock** [comment]
> Gjelder dette fortsatt etter endringene jeg og @klyngen la inn? Tenker du at de ikke skal få hente ut en PAT i det hele tatt?

Endringene dere gjorde stopper kun brukere fra å få tilgang til metoder som bruker RetrieveUser metoden. Admin-endepunktene bruker for eksempel ikke denne metoden, så en admin som har en EndDate før dagens dato vil fortsatt ha tilgang til de med mindre de er slettet fra AAD. Vi kommer nok til å refaktorere oss bort fra RetrieveUser måten å hente bruker på relativt snart. Jeg tenker at EndDate kan sjekkes i PersonalAccessTokenHandler.cs slik at en bruker som har sluttet ikke kan bruke sin token. For vanlig innlogging og tilgang tenker jeg at Azure kan styre det, altså at man sletter brukeren fra AAD.

**Comment by FredrikAugust** [comment]
Yes, da henger jeg med. Takk for oppklaring 

Sendt fra min iPhone
