### ISSUE TITLE
Overtime visualizer viser ikke riktig antall timer

### ISSUE THREAD

**Issue by Trulsaa** [Alv-no/alvtime#406]
<img width="974" alt="Screenshot 2021-09-18 at 12 09 23" src="https://user-images.githubusercontent.com/15033235/133885270-1b70fb3a-4d7b-420d-b050-7d7ecbdfcdb9.png">

I bildet over har jeg nullstilt timebanken. Så har jeg ført 2 overtidstimer på vær av ratene (0.5, 1, 1,5) på samme dag. Det som vises i listen ser ut til å være riktig, men visualizeren viser kun 3 av til sammen 6 timer.

**Comment by palbock** [comment]
@Trulsaa Gjelder fortsatt denne?

**Comment by Trulsaa** [comment]
Jeg klarer ikke reprodusere så jeg closer.
