### ISSUE TITLE
Migrate frontend to Vue 3

### ISSUE THREAD

**Issue by Trulsaa** [Alv-no/alvtime#409]
Guiedes:
https://v3.vuejs.org/guide/migration/migration-build.html
https://johnpapa.net/vue2-to-vue3/

**Comment by Trulsaa** [comment]
Prøvde uten å komme i mål. Virker umulig uten å bytte ut flere store biblioteker som swiper og material-ui

**Comment by FredrikAugust** [comment]
Dette kan jo også trekkes inn i epicen som omhandler å skrive om frontend. Hadde det vært en idé å begynne fra scratch med all UI og beholde så mye som mulig av bizniz logic? Dermed kunne vi startet fra Vue 3

Skulle vi ha satt opp et møte og et kanban-board for Frontend 2?

**Comment by FredrikAugust** [comment]
@Trulsaa @rsletta

**Comment by rsletta** [comment]
> Dette kan jo også trekkes inn i epicen som omhandler å skrive om frontend. Hadde det vært en idé å begynne fra scratch med all UI og beholde så mye som mulig av bizniz logic? Dermed kunne vi startet fra Vue 3
> 
> Skulle vi ha satt opp et møte og et kanban-board for Frontend 2?

@Trulsaa @FredrikAugust: Kanskje sette oss ned på neste AlvFredag, og få noe konkret på bordet?

**Comment by Trulsaa** [comment]
> Dette kan jo også trekkes inn i epicen som omhandler å skrive om frontend. Hadde det vært en idé å begynne fra scratch med all UI og beholde så mye som mulig av bizniz logic? Dermed kunne vi startet fra Vue 3
> 
> Skulle vi ha satt opp et møte og et kanban-board for Frontend 2?

Dersom man tenker å skrive på nytt fra bunden av så er det ingenting som låser oss til å bruke Vue 3. Jeg kan godt tenke meg å lære meg Svelte for eksempel. Det er også fult mulig å serve flere frontender samtidig. Så den nye versjonen av frontenden trenger ikke være future complete før nåværende frontend blir så gammel og utdatert at den må skrus av.

Dersom vi ønsker å ta på oss oppgaven med å oppgradere eksisterende til Vue 3 så handler det for det meste om å skrive ut noen biblioteker som nå blokkerer oppgraderingen. Det er da i hovedsak snakk om `swiper` og `vue-material` som de store jobbene. Det kan jo være gøy å drive med refaktorering også :)

Jeg blir gjerne med på workshop for å finne ut hvordan angripe dette :)
