### ISSUE TITLE
Ønsker meg ansattnummer i User-tabellen i AlvTime

### ISSUE THREAD

**Issue by maikenflowers** [Alv-no/alvtime#418]
Dette for å kunne koble ansattabellen i Airtable med den i dbo.User i Alvtime.
Denne kolonnen må legges inn i dbo.User i tillegg til adminpanelet til AlvTime.

**Comment by Trulsaa** [comment]
@maikenflowers mener du her en ny kolonne i user tabellen i databasen?

**Comment by maikenflowers** [comment]
Jeg mener her en ny kolonne i user-tabellen i databasen.
Det må også være mulig å legge igjen ansattnummeret i adminpanelet slik at
Marcus kan legge inn ansattnummer når det kommer nye ansatte.

man. 31. jan. 2022 kl. 18:10 skrev Truls ***@***.***>:

**Comment by Trulsaa** [comment]
@mikkelcodes Dette er en fin oppgaver å starte med for å lære seg lit .NET :)

**Comment by idatheo** [comment]
TODOs:
1) legg inn kolonne i user tabellen, int
2) Opprett endepunkt (hvis det ikke eksisterer) for å legge inn/ endre ansatt nummer
3) Skriv tester

**Comment by FredrikAugust** [comment]
Heisann, @ragnskah og @idatheo! Er det noe framgang på dette issuet, eller kan det åpnes for at andre kan ta det?

**Comment by idatheo** [comment]
Jeg husker ikke helt hvor langt vi kom. Mener vi var ferdige med noe frontend greier også. Pusher du siste versjon av koden @ragnskah ?

**Comment by HaakonHalvorsen** [comment]
Hvordan ligger det an på denne issuen? Fikk problemer med antall ansatte på infoskjermen på grunn av at vi må gjøre en join mellom airtable og alvtime på Navn, siden AnsattId ikke er synkronisert mellom disse systemene.
