### ISSUE TITLE
Show PBR in frontend dashboard

### ISSUE THREAD

**Issue by palbock** [Alv-no/alvtime#423]
Kan slå sammen "Statistikk" og "Dashboard" fanene.

**Comment by FredrikAugust** [comment]
Hva er PBR? Trenger vi å integrere med f.eks. Tripletex for dette?

**Comment by palbock** [comment]
PBR er faktureringsgrad. Altså fakturerbare timer/forventet antall fakturerte timer (gjerne dobbelsjekk dette mattestykket).
