### ISSUE TITLE
Expand truncated texts

### ISSUE THREAD

**Issue by rsletta** [Alv-no/alvtime#434]
Fix for issue #420 introduce need for expansion of truncated texts, to be able to see and verify the full record.
<img width="378" alt="image" src="https://user-images.githubusercontent.com/12566124/145713007-a4cc3793-68b4-46bf-86a7-bf7d36b7ddf0.png">

**Comment by rsletta** [comment]
Implemented in #436.

**Comment by FredrikAugust** [comment]
Closed this as it is implemented, and opened another issue regarding accessibility in #437.
Great work!
