### ISSUE TITLE
Accessibility for new "expandable project details" feature

### ISSUE THREAD

**Issue by FredrikAugust** [Alv-no/alvtime#437]
With the introduction of #436, you can now click the time entry description to expand it and see additional details.

As it is a clickable element, it should probably have styles to indicate this to maintain good availability.

An idea could be to add `cursor: pointer` to the element, or if you want to get fancy, `cursor: zoom-in` when it's collapsed, and `cursor: zoom-out` when it's expanded.

Some visual cue indicating that it can be clicked could also be helpful.

**Comment by rsletta** [comment]
Great point. Assign the issue to me, and I'll make it happen. 👍
