### ISSUE TITLE
OvertimeVisualizer har en hengende halvtime hvis man bestiller alt

### ISSUE THREAD

**Issue by palbock** [Alv-no/alvtime#471]
Hvis man har x.5 timer i overtidsbanken og bestiller alt viser OvertimeVisualizer forhåndsvisningen at du vil ha 0.5 timer igjen etter bestilling når det egentlig skulle vært tomt.

**Comment by FredrikAugust** [comment]
Er dette kun en grafisk bug?

**Comment by palbock** [comment]
Ja, kun grafisk bug. Hvis man faktisk trykker "Bestill" forsvinner den hengende halvtimen.
