### ISSUE TITLE
Validering for utbetaling: alle timer må være ført

### ISSUE THREAD

**Issue by palbock** [Alv-no/alvtime#499]
Når utbetaling bestilles må det gjøres en sjekk om alle dager har minimum forventet antall timer ført på seg. Kan sjekke dager fra forrige utbetaling til denne.

**Comment by FredrikAugust** [comment]
Så lag en range med dager fra forrige utbetaling (fallback til forrige førte time for de nye) til siste dag i requested utbetaling, og sjekk at alle dager der inne har 7.5t totalt? Finnes det funksjonalitet for dette? Regner med vi da må ta i bruk `EDHelg` og `RedDaysService`.

**Comment by palbock** [comment]
Stemmer. Kanskje fallback til første førte time, ikke forrige, for de som ikke har utbetaling enda. I TimeRegistrationService (tror jeg) finnes det flere steder der vi henter ut `expectedWorkingHours` e.l. som returnerer 7.5 for vanlige dager og 0 for helg og røde dager. Tenker du kan bruke mye av samme logikken.

**Comment by FredrikAugust** [comment]
Perfekt! Prøver bare å _fleshe_ ut issues litt så det er lettere å plukke de opp for folk.
