### ISSUE TITLE
URL on repository frontpage leads to 404

### ISSUE THREAD

**Issue by FredrikAugust** [Alv-no/alvtime#525]

**Comment by rsletta** [comment]
<img width="578" alt="image" src="https://github.com/user-attachments/assets/44ad7b74-a64a-424f-aa23-f0dd6e5c89bc">

**Comment by rsletta** [comment]
@lnordhus @palbock kanskje bare endre til https://alvtime.no/, så vi kan lukke denne? Det er jo ikke feil å lenke til den faktisk tjenesten.

**Comment by palbock** [comment]
@rsletta Done.

**Comment by FredrikAugust** [comment]
Konge, tusen takk
