### ISSUE TITLE
Koble til Tripletex og hent ut data

### ISSUE THREAD

**Issue by FredrikAugust** [Alv-no/alvtime#534]
Det er et ønske om å koble seg på API-et til Tripletex og hente ut data derfra. Denne oppgaven kan derfor være å hente ut _hva_ som helst av informasjon – bare sørge for at koblingen fungerer.

---------

For å komme i gang med Tripletex-integrasjon.

Lag en integrasjons-bruker på https://api.tripletex.io. Hent ut API-nøkler som beskrevet [her](https://hjelp.tripletex.no/hc/no/articles/4409557117713-API-Opprette-brukernøkkel-Integrasjon-for-sluttbruker-og-regnskapsfører). Du får også disse når du oppretter kontoen.

Før du kan gjøre et API-kall må du lage en session token. Anbefaler her å bruke postman-collection til Tripletex for å finne endepunktet og all dataen du må sende inn.

Når du skal logge inn skal du bruke "Basic authentication" og brukernavn=0 (default-bedrift) og passord=<session token i B64-format> (det er det du får når du lager den).

Herifra kan du hente ut annen data som f.eks. `GET /customer` for å hente ut alle kunder.

Merk at `:` og `>` i API-endepunktene er deler av pathen, og er en standard de bruker i TT.

**Comment by FredrikAugust** [comment]
Jeg tror faktisk jeg lar denne ligge for nå, men kan gi noen pekepinner dersom noen andre vil prøve igjen senere. Jeg vil si det ikke er veldig hensiktsmessig å begynne på denne oppgaven før vi har et konkret usecase for koblingen. Det er fordi det må gjøres et valg på hva slags kobling som skal brukes mellom alvtime og tripletex. Skal den enkelte bruker kunne legge inn en API-nøkkel for å hente ut lønn osv.? Eller skal det opprettes en regnskapsførerkonto for Alvtime som kan hente ut større batcher med data, og kanskje også føre timer direkte inn i tripletex?

@Trulsaa @palbock90 har dere noen tanker?

**Comment by palbock** [comment]
> Jeg tror faktisk jeg lar denne ligge for nå, men kan gi noen pekepinner dersom noen andre vil prøve igjen senere. Jeg vil si det ikke er veldig hensiktsmessig å begynne på denne oppgaven før vi har et konkret usecase for koblingen. Det er fordi det må gjøres et valg på hva slags kobling som skal brukes mellom alvtime og tripletex. Skal den enkelte bruker kunne legge inn en API-nøkkel for å hente ut lønn osv.? Eller skal det opprettes en regnskapsførerkonto for Alvtime som kan hente ut større batcher med data, og kanskje også føre timer direkte inn i tripletex?
> 
> @Trulsaa @palbock90 har dere noen tanker?

Jeg tenker vi har lyst på begge deler. Både automatisk innsending av timer o.l., men også at vi kan vise lønn i Alvtime og da også hvor mye penger man vil få utbetalt når man legger inn en bestilling.

**Comment by FredrikAugust** [comment]
Skjønner. Skal vi kanskje bestemme oss for én, spesifisere issuet inn mot det, og så spare det andre til senere?

On a side note, hvis vi skal bruke dette i prod må vi sende inn en søknad om å få alvtime godkjent som en applikasjon.

**Comment by palbock** [comment]
Må diskuteres med Haakon og Marcus for å finne ut hva vi faktisk vil ha.

**Comment by SKollerud** [comment]
Hadde møte med Haakon og Marcus om dette 19.09.2022. De kom ikke på noe reelt behov for å overføre data mellom Tripletex og Alvtime. Foreslår at vi setter denne på vent, til noen kommer med et reelt behov.
