### ISSUE TITLE
Hente flere timentries og vise flere dager/uker når man sviper mot en kant

### ISSUE THREAD

**Issue by Trulsaa** [Alv-no/alvtime#55]
Slik det er nå så lastes all data når appen starter. Man kan så swipe ca 1 år frem eller tilbake. 

Denne oppgraderingen handlere om å laste inn ny data og legge til flere dager/uker når man nærmer seg enden på nåværende data/datoer.

**Comment by FredrikAugust** [comment]
Basert på dette endepunktet

```
https://api.alvtime.no/api/user/TimeEntries?fromDateInclusive=2021-05-03&toDateInclusive=2023-05-07
```

ser det ut som om det allerede er støtte for dette i backend!

**Comment by Trulsaa** [comment]
> Basert på dette endepunktet
> 
> ```
> https://api.alvtime.no/api/user/TimeEntries?fromDateInclusive=2021-05-03&toDateInclusive=2023-05-07
> ```
> 
> ser det ut som om det allerede er støtte for dette i backend!

Ja. Det har vært støtte for det i backend siden starten 😛 Dette issuet handler om å implementere funksjonaliteten i frontend. Når det er sagt så har jeg ikke hørt noen spørre etter det. Så det er nok ikke så høyt prioritert.
