### ISSUE TITLE
Implementer funksjonalitet for stilingsprosent

### ISSUE THREAD

**Issue by palbock** [Alv-no/alvtime#553]
Dersom forventet antall arbeidstimer er mindre enn 7.5, f.eks. ved delvis sykmelding osv skal man få overtid for alle timer jobbet over forventet antall timer. Ferie vil også telle "dobbelt". Dvs at har man 4 dager ferie og jobber kun 50% har man i praksis har man i praksis 8 dager ferie, altså man kan ta fri 8 halve dager eller 4 hele dager. 

Det finnes en variabel som heter anticipatedWorkHours eller HoursInWorkday som muligens kan brukes.

Stillingsprosenten må ha en fra og til dato da man ikke vil at historiske timer skal påvirkes dersom stillingsprosenten endrer seg.

**Comment by palbock** [comment]
Hva må lages:
- Ny tabell i database, EmploymentRate med kolonner UserId, Rate, FromDate, ToDate
- Endepunkter: GET api/user/{userId}/EmploymentRate, POST api/user{userId}/employmentrate (BODY: Rate, FromDate, ToDate), PUT api/user/{userId}/employmentrate (BODY: Rate, ToDate, FromDate)

Logikk:
- Default rate er 100%
- Default ToDate er 31/12/9999
- HoursInWorkday variabel i TimeRegistrationService.cs må tilpasses til å inkludere stillingsprosenten for å beregne forventet antall arbeidstimer for en ansatt. Brukes for å regne ut anticipatedWorkHours.
- TESTER!

Valideringer;
- Bør ikke kunne endre stillingsprosent på en dag der den ansatte har allerede ført overtid. Kan evt trigge utregning av overtid på nytt for gjeldende dager forutsatt at bruker ikke har gjort en utbetaling/ført avspasering som vil påvirkes.

Avklaringer:
- Hva er 50% av en vanlig arbeidsdag? 3.75 timer eller 4 timer? Kan vi runde av til nærmeste halvtime for å slippe å innføre 0.75t.
- Hva med folk som bare jobber timesbasis? Typ kontorvert.

**Comment by palbock** [comment]
Branch er laget - "553-stillingsprosenter". Branchen har EmploymentRate db-modell laget.

**Comment by SKollerud** [comment]
Hadde et møte med Marcus 19.09.2022. For å støtte alle 10% inkrementer av stillingsprosenter, så konkluderte vi med at det beste var å lage støtte for 0,25t timeføring. For han var det litt det samme om alle eller kun de som hadde en laverer stillingsprosent skulle kunne føre 0.25t inkrementer.

Timebasis fungerer vel greit sånn det er i dag? Han hadde ingen kommentarer til det i hvert fall.

**Comment by palbock** [comment]
I utgangspunktet skal det være støtte for 0.25t slik det er i dag så lenge man endrer på inputvalideringen (både frontend og backend), men det kan sikkert være lurt å lage noen ekstra tester i blant annet OvertimeTests.cs, TimeRegistrationServiceTests.cs og PayoutServiceTests.cs som involverer overtid, avspasering og utbetaling med 0.25t for å forsikre seg om at eksisterende logikk ikke blir påvirket.
