### ISSUE TITLE
Gi en warning hvis man ikke fyller inn 7.5 timer i løpet av en dag

### ISSUE THREAD

**Issue by HaakonHalvorsen** [Alv-no/alvtime#558]
**Hvorfor?**
Vi har flere tilfeller tilbake i tid hvor ansatte ikke har fylt opp timene sine (7.5t på en dag) i alvtime. Kanskje gi en warning/varsel på slack om at dette er tilfellet f. eks. ukentlig?

**Comment by palbock** [comment]
@Trulsaa Hva er status på slack-appen? Er det ikke nettopp dette den skal løse?

**Comment by Trulsaa** [comment]
Slack appen gjør dette ja
