### ISSUE TITLE
ValidateTimeEntry bør alltid ta hensyn til stillingsprosent

### ISSUE THREAD

**Issue by palbock** [Alv-no/alvtime#572]
Valideringen som sjekker om man fører mer enn 7.5 timer på en fraværstimekode tar ikke hensyn til stillingsprosent, det burde den. Altså jobber man 50% burde man ikke kunne føre mer enn 3.75 timer på fravær.

**Comment by martehvi** [comment]
@palbock90 Hva definerer du som fraværstimekode? Det ser ut som om det allerede er implementert her? 
![image](https://user-images.githubusercontent.com/47418059/204156158-59b307b7-bc96-45cd-8ad1-44e7be845f75.png)
