### ISSUE TITLE
Adminpanel - Lag kundeliste-komponent

### ISSUE THREAD

**Issue by yvindo** [Alv-no/alvtime#694]
- [x] Search bar
- [x] Listeelement for kunde
- [x] Liste med kunder
- [x] Listeheader fra #698 
- [ ] lage issue på **mulig** forbedret søk funksjonalitet

sp: 8

**Comment by stormboat** [comment]
Foreløpig syntes jeg at den enkle funksjonaliteten som eksisterer for søk fungerer som den skal.
