### ISSUE TITLE
Adminpanel - Design for opprettelse av ny kunder, prosjekter og aktiviteter

### ISSUE THREAD

**Issue by JohanAOstbye** [Alv-no/alvtime#711]
Lag nytt design for:
-  [x] Kunde
-  [x] Prosjekt
-  [x] Aktivitet

sp: 5

**Comment by stormboat** [comment]
### Kommentar til oppgave:
Lagt inn forslag for et godt utgangspunkt, tror ikke det er nødvendig å lage masse forslag nå i første omgang. Tenker de er gode enkle utgangspunkt og hvis man finner ut at det ikke funker i det hele tatt så kan man heller re-iterere over de.
