### ISSUE TITLE
Adminpanel - Legg til ny kunde

### ISSUE THREAD

**Issue by yvindo** [Alv-no/alvtime#724]
- [x] Opprette funksjon for å legge til ny kunde i store
- [x] legge inn + knapp i kundeinfo i header som trigger "opprettelsesmodus"
- [x] Opprettelsesmodus sette alle active-variabler i store til null (fjerner visning av prosjektliste, etc fra kunden man var inne på)
- [x] oppdatere kundeinfo komponenten til å ha funksjonalitet for å legge til ny kunde
- [x] koble opprettelsesknappen i kundeinfo til funksjon i store

sp: 8

**Comment by stormboat** [comment]
Tror denne ble en del større enn 8, mer opp mot 13
