### ISSUE TITLE
Adminpanel - Legg til nytt prosjekt

### ISSUE THREAD

**Issue by yvindo** [Alv-no/alvtime#725]
- [x] Opprette funksjon for å legge til prosjekt i listen til aktiv kunde i store
- [x] legge inn + knapp i prosjektinfo i header som trigger "opprettelsesmodus"
- [x] Opprettelsesmodus setter active project og activity til null (fjerner visning av aktivitetsliste, etc.)
- [x] oppdatere prosjektinfo komponenten til å ha funksjonalitet for å legge til nytt prosjekt
- [x] koble opprettelsesknappen i prosjektinfo til funksjon i store

sp: 8

**Comment by stormboat** [comment]
Gikk relativt fort når lignende komponenter var laget for add/edit customer.
