### ISSUE TITLE
Adminpanel - Mer brukervennlig oppretting av nye ansatte

### ISSUE THREAD

**Issue by palbock** [Alv-no/alvtime#806]
For å slippe å scrolle til bunnen av tabellen hver gang man adder en ny ansatt er det ønskelig å åpne en modal hvor admin kan legge inn data for en ny ansatt, trykke "Lagre" og den nye ansatte blir lagt til i tabellen. Oppdater data (dvs hent data fra nytt fra API) etter modal er lagret for å sikre konsistent data.

Bør gjøres etter eller sammen med #813.

**Comment by rsletta** [comment]
Slåes sammen med #812.
