### ISSUE TITLE
Adminpanel - Endre layout på kundesiden

### ISSUE THREAD

**Issue by palbock** [Alv-no/alvtime#812]
I stedet for en lang liste med tabeller inni tabeller bør kundesiden skrives om til å ha en egen side per kunde. En kundeside kan for eksempel navigeres til via sidemenyen. Det må være mulig å søke etter en kunde. Selve kundesiden med detaljer om hver kunde bør også minimere bruk av tabeller inni tabeller, dette vil også redusere bugs.

![bilde](https://github.com/Alv-no/alvtime/assets/41721443/4d322959-e165-497a-905b-d04b419bb13c)

**Comment by rsletta** [comment]
Note to self: denne må raffineres og brytes ned ytterligere. Se på en revidering av design og brukeropplevelse.
