### ISSUE TITLE
Støtte både komma og punktum for overtidsfaktor

### ISSUE THREAD

**Issue by palbock** [Alv-no/alvtime#815]
Input i tabell støtter per nå kun komma

**Comment by palbock** [comment]
https://mudblazor.com/components/numericfield#setting-culture-and-format

**Comment by rsletta** [comment]
@palbock, denne saken er vel egentlig ikke en bug, men en feature. Input-feltet bruker desimalskille basert på brukerens språkvalg. Spørsmålet vi da må stille oss, er hvordan vi skal angripe det, dersom noen ønsker muligheten til å benytte seg av begge samtidig. Basert på min forståelse av problemstillingen, vil ikke culture and format settings hjelpe oss noe her ettersom det kun gir oss mulighet til å overstyre med språkvalg, og vi derfor ikke vil få en tilstand der begge er tillatt. Problemstilling har blitt diskutert ser det ut til, og jeg fant en mulig hack på https://github.com/MudBlazor/MudBlazor/issues/6181#issuecomment-2053792068, men spørsmålet er selvsagt om man ønsker å bevege seg ned den stien.

Hva tenker du om dette?

https://no.wikipedia.org/wiki/Desimaltegn

(en mulighet er selvsagt å tilby gramatikk-kurs til alle brukere av applikasjonen 🥸 )

**Comment by palbock** [comment]
@rsletta En mulighet er å gjøre som i Alvtime der punktum blir automatisk gjort om til komma før det sendes til backend. Da kan bruker taste inn hva de vil.

Ser forøvrig ut som det er omtrent det de har gjort i den workarounden (så på den etter jeg skrev kommentaren 😅)
