### ISSUE TITLE
Frontend - Mulighet for å legge til kommentar på AlvTime

### ISSUE THREAD

**Issue by klyngen** [Alv-no/alvtime#817]
Under vises en foreslått flyt. Når man trykker på et inputfelt, så dukker det opp en kommentar-knapp. Den skal ha samme utforming som 7,5-timer knappen vi har i dag. Når man trykker på knappen får man opp en modal. Timeføringer som har kommentarer burde utheves.

Fargen rundt kommentar-knappen burde gå igjen i markeringen rundt timeføringen

![alvtime_kommentar_Page 1](https://github.com/user-attachments/assets/901ca424-f944-48ce-9d44-f139db8e3ea4)
![alvtime_kommentar_Page 2](https://github.com/user-attachments/assets/b9996e6e-dba0-4b47-9cb6-0f2a6d4418b3)
![alvtime_kommentar_Page 3](https://github.com/user-attachments/assets/b18b6ed9-daa5-4d3f-9f69-02568eeeb4ad)

**Comment by rsletta** [comment]
Forslag til litt forbedring av flyten:
vi legge den kommentarknappen under boksen når raden er ekspandert, slik at det ikke besudler skjermbildet for alle de som ikke trenger den. Se for dere at de grønne boksene er den snakkeboblen. 
<img width="1437" alt="image" src="https://github.com/user-attachments/assets/2e1e6f28-a3ac-43af-8fdd-83566254786a">
