### ISSUE TITLE
Flutter - Create an empty profile page

### ISSUE THREAD

**Issue by klyngen** [Alv-no/alvtime#827]
We currently have a navigation-bar in the app. However it does not do anything.
Using the defined patterns in the flutter app, do the following

- [ ] Create a new widget, representing a profile page
- [ ] When clicking the various elements in the navigation bar, the user should be routed to the new element
- [ ] The app should not render a `back-button` after navigating. Hint: `Navigator.pushReplacement(context, route);`

**Comment by rsletta** [comment]
@klyngen -> https://github.com/Alv-no/alvtime/pull/835
