### ISSUE TITLE
Fix disalignment when tabbing to next slide

### ISSUE THREAD

**Issue by Trulsaa** [Alv-no/alvtime#9]

**Comment by FredrikAugust** [comment]
Could you provide some more information if this issue is still relevant?

**Comment by Trulsaa** [comment]
Jeg har cursor i nederste boks til høyre og trykker tab. Ønsket oppførsel kan vi ha en idemyldring på, men minste krave bør vel være at swiperen/karusellen hopper helt over på neste side.

![2022-05-04 17 39 29](https://user-images.githubusercontent.com/15033235/166718852-a6f90f6a-49ce-4bad-9338-60a2308b61b4.gif)
